id: 63601d1baa624906a89dfa95adb3a62f
initial_creation_type: ocr
source_metadata:
  volumes:
    cd78912fc3294e758b5213a1d0772892:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: འཇིག་རྟེན་ལས་འདས་པར་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
